stopolice=0
clear
while [ $stopolice -eq 0 ]
do
echo -e "\e[107mPOLICEPOLICEPOLICEPOLICEPOLICEPOLICEPOLICEPOLICEPOLICEPOLICE"
echo -e "\e[107mPOLICEPOLICEPOLICEPOLICEPOLICEPOLICEPOLICEPOLICEPOLICEPOLICE"
echo -e "\e[107mPOLICEPOLICEPOLICEPOLICEPOLICEPOLICEPOLICEPOLICEPOLICEPOLICE"
echo -e "\e[107mPOLICEPOLICEPOLICEPOLICEPOLICEPOLICEPOLICEPOLICEPOLICEPOLICE"
echo -e "\e[107mPOLICEPOLICEPOLICEPOLICEPOLICEPOLICEPOLICEPOLICEPOLICEPOLICE"
echo -e "\e[107mPOLICEPOLICEPOLICEPOLICEPOLICEPOLICEPOLICEPOLICEPOLICEPOLICE"
echo -e "\e[107mPOLICEPOLICEPOLICEPOLICEPOLICEPOLICEPOLICEPOLICEPOLICEPOLICE"
echo -e "\e[107mPOLICEPOLICEPOLICEPOLICEPOLICEPOLICEPOLICEPOLICEPOLICEPOLICE"
echo -e "\e[107mPOLICEPOLICEPOLICEPOLICEPOLICEPOLICEPOLICEPOLICEPOLICEPOLICE"
echo -e "\e[107mPOLICEPOLICEPOLICEPOLICEPOLICEPOLICEPOLICEPOLICEPOLICEPOLICE"
ping localhost -c 1 &> /dev/null
echo -e "\e[106mPOLICEPOLICEPOLICEPOLICEPOLICEPOLICEPOLICEPOLICEPOLICEPOLICE"
echo -e "\e[106mPOLICEPOLICEPOLICEPOLICEPOLICEPOLICEPOLICEPOLICEPOLICEPOLICE"
echo -e "\e[106mPOLICEPOLICEPOLICEPOLICEPOLICEPOLICEPOLICEPOLICEPOLICEPOLICE"
echo -e "\e[106mPOLICEPOLICEPOLICEPOLICEPOLICEPOLICEPOLICEPOLICEPOLICEPOLICE"
echo -e "\e[106mPOLICEPOLICEPOLICEPOLICEPOLICEPOLICEPOLICEPOLICEPOLICEPOLICE"
echo -e "\e[106mPOLICEPOLICEPOLICEPOLICEPOLICEPOLICEPOLICEPOLICEPOLICEPOLICE"
echo -e "\e[106mPOLICEPOLICEPOLICEPOLICEPOLICEPOLICEPOLICEPOLICEPOLICEPOLICE"
echo -e "\e[106mPOLICEPOLICEPOLICEPOLICEPOLICEPOLICEPOLICEPOLICEPOLICEPOLICE"
echo -e "\e[106mPOLICEPOLICEPOLICEPOLICEPOLICEPOLICEPOLICEPOLICEPOLICEPOLICE"
echo -e "\e[106mPOLICEPOLICEPOLICEPOLICEPOLICEPOLICEPOLICEPOLICEPOLICEPOLICE"
ping localhost -c 1 &> /dev/null
done
