stopolice=0
clear
while [ $stopolice -eq 0 ]
do
echo -e "\e[107mPOLICEPOLICEPOLICEPOLICEPOLICEPOLICEPOLICEPOLICEPOLICEPOLICEPOLICEPOLICE"
echo -e "\e[107mPOLICEPOLICEPOLICEPOLICEPOLICEPOLICEPOLICEPOLICEPOLICEPOLICEPOLICEPOLICE"
echo -e "\e[107mPOLICEPOLICEPOLICEPOLICEPOLICEPOLICEPOLICEPOLICEPOLICEPOLICEPOLICEPOLICE"
echo -e "\e[107mPOLICEPOLICEPOLICEPOLICEPOLICEPOLICEPOLICEPOLICEPOLICEPOLICEPOLICEPOLICE"
echo -e "\e[107mPOLICEPOLICEPOLICEPOLICEPOLICEPOLICEPOLICEPOLICEPOLICEPOLICEPOLICEPOLICE"
echo -e "\e[107mPOLICEPOLICEPOLICEPOLICEPOLICEPOLICEPOLICEPOLICEPOLICEPOLICEPOLICEPOLICE"
echo -e "\e[107mPOLICEPOLICEPOLICEPOLICEPOLICEPOLICEPOLICEPOLICEPOLICEPOLICEPOLICEPOLICE"
echo -e "\e[107mPOLICEPOLICEPOLICEPOLICEPOLICEPOLICEPOLICEPOLICEPOLICEPOLICEPOLICEPOLICE"
ping localhost -c 1 &> /dev/null
echo -e "\e[106mPOLICEPOLICEPOLICEPOLICEPOLICEPOLICEPOLICEPOLICEPOLICEPOLICEPOLICEPOLICE"
echo -e "\e[106mPOLICEPOLICEPOLICEPOLICEPOLICEPOLICEPOLICEPOLICEPOLICEPOLICEPOLICEPOLICE"
echo -e "\e[106mPOLICEPOLICEPOLICEPOLICEPOLICEPOLICEPOLICEPOLICEPOLICEPOLICEPOLICEPOLICE"
echo -e "\e[106mPOLICEPOLICEPOLICEPOLICEPOLICEPOLICEPOLICEPOLICEPOLICEPOLICEPOLICEPOLICE"
echo -e "\e[106mPOLICEPOLICEPOLICEPOLICEPOLICEPOLICEPOLICEPOLICEPOLICEPOLICEPOLICEPOLICE"
echo -e "\e[106mPOLICEPOLICEPOLICEPOLICEPOLICEPOLICEPOLICEPOLICEPOLICEPOLICEPOLICEPOLICE"
echo -e "\e[106mPOLICEPOLICEPOLICEPOLICEPOLICEPOLICEPOLICEPOLICEPOLICEPOLICEPOLICEPOLICE"
echo -e "\e[106mPOLICEPOLICEPOLICEPOLICEPOLICEPOLICEPOLICEPOLICEPOLICEPOLICEPOLICEPOLICE"
ping localhost -c 1 &> /dev/null
done
